LSS-Manager/lss-manager-v3

lss-manager-v3/lss-manager-v3.dev.js
Dutch translation added to the script
=> Dutch Translation

modules/lss-missionHelper/missionHelper.user.js
Update for Assistentie treinconducteur (mel) and Aggressive Passenger (MC)
=> Update for 2 Missions (Mel and MC)

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-AAO-Zaehler/aao-zaehler.js
Ich hoffe die Übersetzungen stimmen so...
=> Aao zaehler

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-destinationFilter/DestinationFilter.user.js
UI wie immer noch kacke und sollte noch aufgehübscht werden. @lostdesign
=> #149: Introduce DestinationFilter

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-centermap/Centermap.user.js, modules/lss-destinationFilter/DestinationFilter.user.js, modules/lss-managedsettings/ManagedSettings.user.js, modules/lss-statusDispatching/statusDispatching.user.js
Hallo,
da die ManagedNotificationSettings aus Zeitgründen noch nicht integriert werden konnten, habe ich die nicht Notificationsettings betreffenden Teile in diesen Branch zusammen gezogen, um diese getrennt davon integrieren zu können.
=> Cherry-picked non-notificationAlert related changes

modules/lss-missionKeyword/missionKeyword.user.js
=> two sonar bug fixxes

modules/lss-missionHelper/missionHelper.user.js
LSS und Mel updatet. Und 2 Sonarbugs gefixxt
=> Update to new missions

modules/lss-missionHelper/missionHelper.user.js
The Last of day. Missionchief Mission added
=> MC Mission added

modules/lss-missionHelper/missionHelper.user.js
=> Fix one German Mission

modules/lss-missionHelper/missionHelper.user.js
Update for Missions in all games
=> Update for Missions in all games

modules/lss-missionHelper/missionHelper.user.js
=> Fix one mission

modules/lss-missionHelper/missionHelper.user.js
New Mission from MC,MEL and LSS added.
=> New Mission adding

modules/lss-missionHelper/missionHelper.user.js
Jo hier die 3 neuen WaWe Missionen :)
=> ADDED 3 Missionen wo der WaWe benötigt wird

modules/lss-missionHelper/missionHelper.user.js
=> New Missions added

lss-manager-v3/css/main.css, lss-manager-v3/helperfunctions.js, modules/lss-dashboard/dashboard.html, modules/lss-dashboard/dashboard.user.js
- Wasserrettung wurde unter Dashboard hinzugefügt sowie unter der Wachenplanung.
- Bei der BePo(Polizeitab Wachenplannung) habe ich die Autos erhöht für das kommende WaWe update.
aus.
- Aus `col-md-3` hab ich `col-md-2` gemacht, sonst hätte es nicht von der aufteilung gepasst.
- Die Wasserrettungsautos vom thw habe ich beim THW mit hinzugefügt in der helperfunctions. Da ich finde THW sollte zu THW :P 
- Wasserrettung auch in der main.css added :D 
Wenn es verschönerungen geben sollte, könnt ihr gerne einwände gelten machen :) 
Ist von meinem Vorschlag #235
=> 235 Dashboard WR/THW

modules/lss-missionHelper/missionHelper.user.js
ein komma vergessen. ich dödel
=> little fix

lss-manager-v3/helperfunctions.js
Mit der Helperfunctions sollte das Problem aus #246 evtl. gefixxt sein. 
Zumindest über meinen server kam das gleiche ergebnis raus mit der aktuellen im masterbranch tätigen helperfunctions. 
Habe ich aber die aus dem dev genommen, wurde mir sofort alles angezeigt und auch die heatmap funktioniert soweit wieder.
=> Dashboard/Heatmap fix?

modules/lss-missionHelper/missionHelper.user.js
Joa die neuen Missionen. Diesmal sollte ich nix vergessen haben....
=> Added the new missions at 18.8

modules/lss-missionHelper/missionHelper.user.js
=> Missions from 8.9 added

modules/lss-missionHelper/missionHelper.user.js
=> Added Missions from 15.9

lss-manager-v3/helperfunctions.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
https://forum.leitstellenspiel.de/index.php/Thread/12116-GRTW/?postID=198387#post198387
Edit: 29.9 : Reviewed nach den einsätzen, dann adde ich die nachher erst noch bevor hier nachgeguckt werden kann :D
=> Added GRTW to helperfunctions/ Mission 29.9

lss-manager-v3/helperfunctions.js
Die Neuen Niederländischen Autos aka BPOL geaddet :D
=> Added Mobiele Eenheid to helperfunctions

lss-manager-v3/helperfunctions.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
Dazu wieder in der Helperfunctions den einen wagen umbenannt wie er in den Einsätzen steht.
Und ich hoffe die Stichworte sind so richtig, sonst können sie gerne noch geändert werden (bei den niederländischen mit Person vermisst(246-248))
Sonst bitte nicht schlagen ;(
=> Missions Added from 13.10

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
fix some missions at Mel and LSS
added one new mission at Mel
=> Added /Fix Missions

lss-manager-v3/css/main.css
Ist das hier richtig eingefügt?
=> Class für Counter hinzugefügt

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-eventmissions/eventmission.user.js
Zeigt mit [Jeweiliges Event] die Eventeinsätze die von Sebastian aktiviert werden können.
=> Eventeinsatz Markierung

modules/lss-aao-time/lss-aao-time.user.js
Kann dadurch auch im dunklen LSS Design gelesen werden.
(Hoffe das war jetzt so richtig eingetragen :D )
=> Bessere Lesbarkeit

lss-manager-v3/helperfunctions.js, modules/lss-TailoredTabs/TailoredTabs.user.js, modules/lss-eventmissions/eventmission.user.js, modules/lss-keyboardAlert/lss-keyboardAlert.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
Da sich die Erweitung bei Meldkamer noch um ein paar Tage verzögert, möchte ich nicht, das sich die Leute beschweren, das etwas fehlt. Daher hier das Airport Update für den LSS. 
Mit ein paar fixes von Eventmissions und Keyboardalert.
Beim Missionhelper, Missionkeyword und Tailored Tabs wurden die Flughafen Sachen geadded
=> Flughafenfeuerwehr Erweiterung LSS

modules/lss-missionDate/missionDate.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
missionHelper:
- fixed some wrong messages
- fixed some spelling mistakes
missionKeyword:
- revised special event names
- removed space from mass casualty markers
missionDate:
- used correct abbreviation for March
=> Dutch missionHelper and missionKeyword fixes

modules/lss-aao-time/lss-aao-time.user.js
Das löst das Problem nicht, aber eine Meldung sorgt für Transparenz und es kommt zu keinen Exceptions mehr.
=> Show warning when there are unsupported vehicle combinations in aao

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-AAO-Zaehler/aao-zaehler.js
Neuer Button, der es ermöglicht, alle Zähler in der AAO zurückzusetzten.
=> AAO-Zähler Reset-Button

modules/lss-FMS5InMap/FMS5InMap.user.js, modules/lss-WachenHoverStati/WachenHoverStati.user.js, modules/lss-WachenplanungOnMap/WachenplanungOnMap.user.js, modules/lss-WachenplanungOnMap/readme.md, modules/lss-centermap/Centermap.user.js
Joa ein paar Fixxes. Ich hasse es :D
=> Mapkit Translations fixxes

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-verbandsverwaltung/verbandsverwaltung.js
Mal so die erste Version einer Verbandsverwaltung.
Fügt einfach eine kleine Übersicht mit
- Zahl der Online-Mitglieder in Relation zur gesamt-Mitgliederzahl des Verbandes
- Aktueller Stand der Verbandskasse (falls aktiv)
- Wie viele Credits der Verband schon verdient hat (was in der Verbandsliste steht)
in die bereits bestehende Verbands-Dropdown ein.
Erweiterungen (auch nur deren Ideen) gerne erwünscht.
Liebe Grüße Jan
=> Verbandsverwaltung

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
Sebastian hat etwas neues eingebaut und nu is der fix da...
=> WF Einsätze und fix

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-overview/overview.js
der @KBOE2 hat eine Fahrzeugübersicht gemacht. mit dem PR soll es nun für alle Freigegeben werden :) . Von meiner Seite aus ist es aprroved, da es ohne Probleme und sonstiges funktioniert.
Das bei 2-3 Sachen undefined steht, liegt daran, das wir dort keine Daten hatten 
#374
=> Fahrzeugübersicht Ingame

modules/lss-overview/overview.js
Gebäude hinzugefügt, ebenfalls Informationen von MC und Meldkamer, die vorher nicht bekannt waren
=> Overwiev erweiterung

lss-manager-v3/lss-manager-v3.dev.js
DAmit angezeigt wird, welche Module nicht mit einander kompatibel ist. Gefixxt nach Wochen/Monaten von @KBOE2 😂😂😂🤣🤣🤣
=> Collission-Message fix

lss-manager-v3/css/main.css
Bessere Formatierung & unnötige whitespaces entfernt.
=> clean main.css

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
The Missions from 7.12 and some deleted 100% requirements
=> Missions 7.12 and someone

modules/lss-missionHelper/missionHelper.user.js
=> Rettungstransportwagen zu Rettungswagen :D

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
=> LSS/MEL Missions 04.01.2019

modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
=> Missions 18012019

modules/lss-missionHelper/missionHelper.user.js
https://www.facebook.com/missionchief/photos/a.471813122977117/1161560220669067/?type=3&theater
=> Cars removed from MC Mission 230,231

modules/lss-dashboard/dashboard.html
Da wir sie eh aktuell nicht nutzen bzw noch nie genutzt haben, habe ich sie erstmal in der datei ausgeklammert, sodass sie nicht mehr angezeigt wird. Das Suchfeld habe ich drin gelassen, da es seine Funktion erfüllt.
Ich habe das jetzt gemacht, da jemand im Forum gefragt hat, was es damit auf sich hat.
Bitte einmal rüber gucken, sodass wir es spätestens Freitag dann mit in den Master hauen können :)
=> dashboard gruppierung rausgenommen

modules/lss-redesign-01/redesign-01.user.js, modules/lss-searchMissions/searchMissions.user.js
Siehe #442 
Die Fehler soweit behoben, das es funktioniert. 
Einsätze suchen (searchmissions) mit in die neue Einsatzsuchleiste getan. dann nutzen wir nicht mehr das Orte suchen feld :)
=> Fixxes for new lss feature

lss-manager-v3/css/main.css, lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-dashboard/dashboard.user.js, modules/lss-eventmissions/eventmission.user.js, modules/lss-extendedBuilding/extendedBuilding.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-redesign-01/redesign-01.user.js
Today Missions from the Games
Refactoring RenameFZ by @KBOE2
=> Missions 12042019 and RenameFZ refactoring

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-overview/overview.js
and add some Water things to missions
=> New Car LSS 16042019

modules/lss-destinationFilter/DestinationFilter.user.js
Das der Unterschied zwischen eine kleinen `h` und einem grossen `h` so viel ausmachen kann :D
=> fixing #477

modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
Today's Missions and beautify code from renamefz
=> Missions and someone

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-statuscount/statuscount.js
Today Missions,
AAO-Search Removed da Sebastain hinzugefügt hat im Spiel
Statuscount alle 5 min Update
=> Missions 07062019 and two other things

modules/lss-WachenHoverStati/WachenHoverStati.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-overview/overview.js, modules/lss-statuscount/statuscount.js
Today Missions,
Fix Overview
Statuscount sync via click on statusheader
Wachenhoverstati Sortable by Names
=> Missions 14062019 and Improvments

modules/lss-TailoredTabs/TailoredTabs.user.js
Wurde nun umgesetzt nach einer längeren Zeit.
=> BPol entfernt

lss-manager-v3/helperfunctions.js, lss-manager-v3/lss-manager-v3.dev.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-aao-search/aao-search.user.js, modules/lss-overview/overview.js
AAO-Search wieder hinzugefügt und ein wenig angepasst an die von LSS. komplett Übernahme davon müsste sich wer anders angucken.
Dann das neue MC Car EMS Chief 
und zu guter letzt
das neue MEL Car RR aka Rapid Responder :)
=> Some Changes

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js
Heatmap removed aufgrund der Fehler
Heutige Missionen
=> Missions today and heatmap

modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-overview/overview.js, modules/lss-saveVGE/saveVGE.user.js
Today Missions
Kleinwache POL zu Overview und RenameFZ added
Some Fixxes in Overview thx to Jenkins
Improvments in RenameFZ and saveVGE thx to KBOE :D
=> Missions today and improvments

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-overview/overview.js
Missions today
Discord Link added to Appstore
PoliceStation Small added for MC
some fixxes in overview thx to Jenkins
=> Missions and added new stuff

modules/lss-missionHelper/missions.de.json, modules/lss-missionHelper/missions.en.json, modules/lss-missionHelper/missions.nl.json
=> :boom: [missionHelper] Add all Missions

modules/lss-MissionOut/MissionOut.user.js, modules/lss-missionHelper/loadMissionData.nl.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de.json, modules/lss-missionHelper/missions.en.json, modules/lss-missionHelper/missions.nl.json
Iconhide raus missionout
großeinsätze bei den games mit in die einsatzliste
=> 🔀 missionOut, missionHelper

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-managedsettings/ManagedSettings.user.js, modules/lss-shareAlliancePost/ShareAlliancePost.js
Hi Leute,
bitte übernehmt das Modul in den LSSM.
Die Standalone ist sehr begehrt und ich will sie nicht länger pflegen.
=> ShareAlliancePost 4 LSSM

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-fms7-target/Fms7Target.js
Es fehlen Übersetzungen und ein vernünftiger End-To-End Test.
Durch diverse Lazy-Loading Änderungen im Basis Spiel, ist das mittlerweile etwas ekelhafter umzusetzen wie damals in meiner Standalone Version. Vom Funktionsumfang ist es daher gegenüber der Standalone etwas abgespeckt (erstmal). Sofern es stabil läuft, kann man sich über Erweiterungen Gedanken machen.
=> Fms7Target 4 LSSM

lss-manager-v3/lss-manager-v3.dev.js, modules/newYear.js
Happy New Year from the LSS-Manager Team
Co-Authored-By: Jan <kboe2@users.noreply.github.com>
Co-Authored-By: wellá <lostdesign@users.noreply.github.com>
Co-Authored-By: Tsumiki <tsumiki-chan@users.noreply.github.com>
=> :sparkles: [Core] New Year Update :P

modules/lss-layout-04/layout-04.user.js
Co-Authored-By: types140 <types140@users.noreply.github.com>
=> :bug: [Layout04] Fixxing double VGE

modules/lss-shareAlliancePost/ShareAlliancePost.js
See: [https://canary.discordapp.com/channels/254167535446917120/632909910895755264/686199421100490816](https://discordapp.com/channels/254167535446917120/632909910895755264/686199421100490816)
=> Fixed wrong rounding

modules/lss-missionHelper/missionHelper.user.js
enhanced italian translation of missionHelper module
=> italian translation missionHelper

modules/lss-destinationFilter/DestinationFilter.user.js, modules/lss-missionHelper/loadMissionData.de_DE.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-sumDailyMissions/sumDailyMissions.user.js
🚀 [SumDailyMissions] FR Translations 
🐛 [SumDailyMissions] Fix EN Translation
✨ [DestinationFilter] Hide under x Beds
=> 🚀 [MissionHelper] DE Mission 08.05

modules/lss-managedsettings/ManagedSettings.user.js, modules/lss-overview/overview.js, modules/telemetry/telemetry.user.js
AT vihicles and the DA-VL added to the overview module.
Add the coins price for the "Hondengeleider"
Also edit some translations
=> Update Dutch overview + translations

modules/lss-AAO-Zaehler/aao-zaehler.js, modules/lss-missionHelper/loadMissionData.de_DE.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionKeyword/missionKeyword.user.js
=> 🚀 [MissionHelper] DE Missions 15.05

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-creditserweiterung/creditserweiterung.user.js, modules/lss-dashboard/dashboard.user.js, modules/lss-layout-04/layout-04.user.js, modules/lss-missionHelper/loadMissionData.de_DE.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionKeyword/missionKeyword.user.js, modules/lss-verbandsverwaltung/verbandsverwaltung.js
🐛 [Layout04] Doppel VGE removed
=> ✨ [Core] RHS Added to DE

modules/lss-TailoredTabs/TailoredTabs.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionKeyword/missionKeyword.user.js
[TailoredTabs] RHS added to this
[MissionHelper] Add ID 59 BR
=> 🚀 [MissionHelper] Fix Missions

modules/lss-overview/overview.js
@Piet2001 Kan je deze nakijken?
=> Corrections SL and buildings

modules/lss-missionHelper/missionHelper.user.js
'Löschfahrzeuge oder Rüstwagen oder GKW', translated in Dutch
=> Fix NL translate

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.pl_PL.json
MissionKeyword is coming soon for PL :)
=> ✨ [Core] UK EMS and PL Waterresuce Update

modules/lss-TailoredTabs/TailoredTabs.user.js, modules/lss-extendedBuilding/extendedBuilding.js, modules/lss-missionHelper/missionHelper.user.js, modules/lss-shareAlliancePost/ShareAlliancePost.js, modules/lss-sumDailyMissions/sumDailyMissions.user.js
ExtendedBuilding PL Fix
MissionHelper AU Fix
ShareAlliancePost Cache TestFix
TailoredTabs Anh Hund add to RHS
sumDailyMissions Credits add
=> 🚀 [Core] Some Improvments

modules/lss-AAO-Zaehler/aao-zaehler.js, modules/lss-sumDailyMissions/sumDailyMissions.user.js
Translations NL of the new settings at aaozaehler.
And could you please look to the code I have changed of sumDailyMissions. 
This was my idea after a couple of reactions I heard of Dutch people on the new update.
=> Translation aaozaehler NL and update background sumDailyMissions?

modules/lss-missionHelper/missionHelper.user.js, modules/lss-sumDailyMissions/sumDailyMissions.user.js
🐛 [missionHelper] Bugfix when helper not loaded
=> 🚑 [SumDailyMissions] Fix don't sum after new update

modules/lss-eventmissions/eventmission.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-missionHelper/missions.uk_UA.json
And Fix Eventmissions thx to Jan
=> 🚀 [MissionHelper] Missions 29.06

modules/lss-notification_alert/Notification_alarm.user.js
Sorry, now from the correct branche
=> [lss-notification_alert] Add color of chat text for readability in dark mode

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/nb_NO.json, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-missionHelper/missions.uk_UA.json
🐛 [MissionHelper] Hotel Expansion Fixxes
🐛 [MissionHelper] Remove unused mission FI
🌐[Core] Redningsbil nb_NO :) 
🚀 [MissionHelper] 20.07 4 p.m.
=> 🚀 [MissionHelper] 20.07 10/11 a.m. 

modules/lss-missionHelper/missions.de_DE.json, modules/lss-verbandsverwaltung/verbandsverwaltung.js
🐛 [verbandsverwaltung] Fix design
=> 🚀 [MissionHelper] DE Mission 24.07

modules/lss-overview/overview.js
@Piet2001 Kan jij deze nakijken  of die klopt?
=> [Overview] NL MMT-update 21/7/2020 and fix OVD-G/RR + Rename NL of  06/08

modules/lss-missionHelper/missions.de_DE.json, modules/lss-overview/overview.js
🌐 [overview] More Translate NL
=> 🚀 [MissionHelper] DE Mission 07.08

lss-manager-v3/css/main.css, modules/lss-WachenplanungOnMap/WachenplanungOnMap.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
✨ [WpOM] Add RHS
🚀 [WpOM] mark_bp psonder add
=> 🚀 [MissionHelper] Missions 10.08

modules/lss-overview/overview.js
- Add shortnames and longnames
- Change special WOA: Remove need DA, add need PM-OR
-  Sort list alphabetically
=> [Overview] NL update

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
✨ [MissionHelper] JSON API Updates :)
=> ✨ [MissionHelper] K9 de_DE

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/de_DE.json, modules/lss-missionHelper/i18n/en_US.json, modules/lss-missionHelper/i18n/es_ES.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-overview/overview.js, modules/lss-shareAlliancePost/ShareAlliancePost.js
🚀 [MissionHelper] 24.08
🚀 [Overview] de_DE 🐕 add
✨ [Overview] add Brushvehicles to Overview US 
🐛 [MissionHelper] Water demand not English
=> ✨ [Core] Water Amount add to en_US

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js
Hopefully this change the name of the DB-K in the dashboard.
=> [NL] DB to DB-K

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/de_DE.json, modules/lss-missionHelper/i18n/en_US.json, modules/lss-missionHelper/i18n/pl_PL.json, modules/lss-missionHelper/i18n/sv_SE.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
✨ [Core] Water Demand pl_PL
✨ [Core] 🇸🇪 Wildland Update Part 1
✨ [MissionHelper] Default 30% Patient Transport
✨ [MissionHelper] allow_arff_instead_of_lf for de_DE
=> ✨ [Core] Some new Things

modules/lss-missionDate/missionDate.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.pl_PL.json
:rocket: [MissionHelper] PL add two some missions for water demand
[MissionDate] fix SE
=> :rocket: [MissionHelper] DE 04.09

modules/lss-shareAlliancePost/ShareAlliancePost.js
Thanks to @Ron31 and @JRH-1997
=> ♻️⚡️🔀[SAP] Credits to LocalStorage

modules/lss-shareAlliancePost/ShareAlliancePost.js
i hope it is right. otherwise beat me and change it yourself :P
=> :zap: [SAP] Time to get aMissions Update to 1 day

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-overview/overview.js
=> :rocket: [Missionhelper] DE Mission 11.09

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/fr_FR.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json
[MissionHelper] Changed Emoji
[MissionHelper] Some Missionchanges
=> :sparkles: [Core] 🇫🇷 Police Update

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/en_GB.json, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-overview/overview.js
🚀 [MissionHelper] Alcoholic intoxication onlyRD
🐛 [MissionHelper] Fix Alc intox mission
**_Do not merge. Only when the announcement is out :P_**
=> ✨ [Core] New 🇬🇧 Update

modules/telemetry/telemetry.user.js
=> 🌐 [v4 note] add clarification LSSM, NOT game!

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.sv_SE.json, modules/telemetry/telemetry.user.js
US New Missions?
SV New Mission?
Some Mission fixxes
🌐 🇳🇱 v4 note
=> 🚀 [MissionHelper] DE Mission 09.10

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.sv_SE.json
=> :rocket: [Missionhelper] DE Mission 16.10

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-overview/overview.js
:bug: [Overview] Fix wtank wildlandengines
=> :rocket: [MissionHelper] Missions 26.10

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.nl_NL.json
And some fixxes in other countries
=> :rocket: [MissionHelper] 13.11 DE Mission

modules/lss-missionHelper/missions.de_DE.json, modules/telemetry/telemetry.user.js
🔥 ⏪ [telemetry] remove v4betahint
=> 🚀 [Mission] DE Mission 20.11

lss-manager-v3/lss-manager-v3.dev.js
https://forum.leitstellenspiel.de/index.php?thread/19561-skriptwunsch-kreis-landesgrenzen
Wie hier vorgeschlagen die Änderung zum Zeigen der Kartengrenzen innerhalb der Profil Ansicht
=> Zeige Kreisgrenzen im Profil

modules/lss-WachenplanungOnMap/WachenplanungOnMap.user.js, modules/lss-clock/clock.user.js
Quick'n'dirty fix for clock & WachenplanungOnMap and the overlay problems with v4
=> 💄 🐛 fix clock&planningOnMap overlay bug with v4

modules/lss-WachenplanungOnMap/WachenplanungOnMap.user.js, modules/lss-clock/clock.user.js
Reverts LSS-Manager/lss-manager-v3#852
Changes wont work and made it even worse
=> Revert "💄 🐛 fix clock&planningOnMap overlay bug with v4"

modules/lss-WachenplanungOnMap/WachenplanungOnMap.user.js, modules/lss-clock/clock.user.js
Reverts LSS-Manager/lss-manager-v3#853
=> Revert "Revert "💄 🐛 fix clock&planningOnMap overlay bug with v4""

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/de_DE.json, modules/lss-missionHelper/missions.de_DE.json
=> ✨[Core] New "Car" add to de_DE

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/nb_NO.json, modules/lss-missionHelper/i18n/pt_PT.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.pt_PT.json
🚀🐛[Missions] Some Mission Changes
=> ✨[Core] 🇵🇹 🇳🇴 ContentPack

modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.nb_NO.json
=> 🚀 [Missions] Missions 08.01.2021

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.nb_NO.json
🚀[Missions] Add new things to de_DE
=> 🐛[MH] Fix nb_NO Mission

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.nl_NL.json
=> 🚀 [Missions] 15.01

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json
=> ✨[mH] pt_PT aniversário 1 year

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/en_US.json, modules/lss-missionHelper/i18n/it_IT.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.it_IT.json
✨[Core] 🛥️IT CP
✨[Core] US 🚑 Update 1
=> ✨[Core] 2 CP's

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/sv_SE.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
Today de_DE Mission
Valentinsday Missionpack to all Countrys
=> ✨[Core] Water demand sv_SE

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-creditserweiterung/creditserweiterung.user.js, modules/lss-missionHelper/i18n/pl_PL.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.pl_PL.json
🚀 [Missions] 12.02
🐛 [CreditsVerwaltung] improved regex (also /?)
=> ✨[Core] PL 🚑 Update

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/en_AU.json, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.sv_SE.json
=> ✨[Core] AU 🚑 Update

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-destinationFilter/DestinationFilter.user.js, modules/lss-missionHelper/i18n/en_AU.json, modules/lss-missionHelper/i18n/fr_FR.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
✨ [DestinationFilter] x own Hospitals and hide settings
🚀 [Missions] place_array add
=> ✨[Core] FR 🚑 Update

modules/lss-destinationFilter/DestinationFilter.user.js, modules/lss-missionHelper/missions.de_DE.json
🐛 [DestinationFilter] x own Hospitals fix
=> 🚀 [Missions] 26.02

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.sv_SE.json
fire_alarm_system_possible add
=> 🚀 [Missions] 01.03

modules/lss-destinationFilter/DestinationFilter.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.sv_SE.json
🐛 [destinationFilter] potential fix
=> 🚀 [Missions] 05.03

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-missionHelper/missions.uk_UA.json, modules/lss-sumDailyMissions/sumDailyMissions.user.js
=> 🚀 [Missions] 29.03

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-missionHelper/missions.uk_UA.json
en_US is missing. coming later this day
=> 🚀 [Missions] 05.04

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.fr_FR.json
some add allow_ktw_instead_of_rtw to fr_FR
=> 🚀 [Missions] 23.04

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json, modules/lss-missionHelper/missions.uk_UA.json, modules/lss-saveVGE/saveVGE.user.js
💄 [saveVGE] remove forced white bg
=> 🚀 [Missions] 03.05

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/en_GB.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json
=> ✨ [Core] 🚑HART 2 CP add

modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json
👽️[mH] date_start/end to ISO Format
=> 🚀 [Missions] 28.05

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/pt_PT.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json
=> ✨ [Core] 🌳🔥🚒CP 🇵🇹

modules/lss-extendedBuilding/extendedBuilding.js, modules/lss-missionHelper/i18n/de_DE.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.cs_CZ.json, modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_AU.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json
and activate subsequent for de_DE
🐛[eb] fix?
=> 🚀 [Missions] 09.07 

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.nl_NL.json
Remove Police from Contaminated ice cream cart de_DE
add missing "generated_by": "Water rescue" to en_US and nl_NL
=> 🐛 [MH] Fix

lss-manager-v3/lss-manager-v3.dev.js, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pt_BR.json
=> Add an .navbar-right, to be sure

modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-userid/lss-userId.user.js
and add user-id after the lssm dropdown
=> 🚀 [Missions] 02.08

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/de_DE.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.en_US.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.pt_PT.json, modules/lss-missionHelper/missions.sv_SE.json
=> ✨ [Core] 🚚🌊CP 🇩🇪

lss-manager-v3/helperfunctions.js, modules/lss-RenameFZ/renameFZ.user.js, modules/lss-missionHelper/i18n/es_ES.json, modules/lss-missionHelper/missionHelper.user.js, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.es_ES.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.ja_JP.json, modules/lss-missionHelper/missions.ko_KR.json, modules/lss-missionHelper/missions.pt_BR.json, modules/lss-missionHelper/missions.ro_RO.json, modules/lss-missionHelper/missions.ru_RU.json, modules/lss-missionHelper/missions.sv_SE.json
=> ✨ [Core] 🔥🔥🔥🚒CP 🇪🇸

modules/lss-missionHelper/missions.da_DK.json, modules/lss-missionHelper/missions.de_DE.json, modules/lss-missionHelper/missions.en_GB.json, modules/lss-missionHelper/missions.fi_FI.json, modules/lss-missionHelper/missions.fr_FR.json, modules/lss-missionHelper/missions.it_IT.json, modules/lss-missionHelper/missions.nb_NO.json, modules/lss-missionHelper/missions.nl_NL.json, modules/lss-missionHelper/missions.pl_PL.json, modules/lss-missionHelper/missions.pt_PT.json
=> 💤 1001 Nights 💤

lss-manager-v3/helperfunctions.js
=> [fr_FR] Add Sauvetage Cotier

modules/lss-extendedBuilding/extendedBuilding.js
This fixes https://forum.leitstellenspiel.de/index.php?thread/11166-lss-manager-v3/&postID=466928#post466928
=> 🐛 [eb] fix extensions list

lss-manager-v3/helperfunctions.js
=> 🌐 add missing en_US, en_GB and sv_SE vehicles

lss-manager-v3/lss-manager-v3.dev.js, lssm-v3.user.js
we do not have a stable-beta system anymore and the uid query-param reduces caching rate.
=> ✨ remove uid from urls

lss-manager-v3/helperfunctions.js
=> ✨ [core] de_DE Drone Update
